// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/signal.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityStoreConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef    string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	LocalId        string                 `protobuf:"bytes,2,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	DeviceId       uint32                 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RegistrationId uint32                 `protobuf:"varint,4,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdentityStoreConfig) Reset() {
	*x = IdentityStoreConfig{}
	mi := &file_proto_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityStoreConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityStoreConfig) ProtoMessage() {}

func (x *IdentityStoreConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityStoreConfig.ProtoReflect.Descriptor instead.
func (*IdentityStoreConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityStoreConfig) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

func (x *IdentityStoreConfig) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *IdentityStoreConfig) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *IdentityStoreConfig) GetRegistrationId() uint32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

type SpaceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceRef      string                 `protobuf:"bytes,1,opt,name=space_ref,json=spaceRef,proto3" json:"space_ref,omitempty"`
	IdentityRef   string                 `protobuf:"bytes,2,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	RoomRef       string                 `protobuf:"bytes,3,opt,name=room_ref,json=roomRef,proto3" json:"room_ref,omitempty"`
	EventbusRef   string                 `protobuf:"bytes,4,opt,name=eventbus_ref,json=eventbusRef,proto3" json:"eventbus_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceConfig) Reset() {
	*x = SpaceConfig{}
	mi := &file_proto_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceConfig) ProtoMessage() {}

func (x *SpaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceConfig.ProtoReflect.Descriptor instead.
func (*SpaceConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceConfig) GetSpaceRef() string {
	if x != nil {
		return x.SpaceRef
	}
	return ""
}

func (x *SpaceConfig) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

func (x *SpaceConfig) GetRoomRef() string {
	if x != nil {
		return x.RoomRef
	}
	return ""
}

func (x *SpaceConfig) GetEventbusRef() string {
	if x != nil {
		return x.EventbusRef
	}
	return ""
}

type EnvelopeTriggerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRef     string                 `protobuf:"bytes,1,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	IdentityRef   string                 `protobuf:"bytes,2,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeTriggerConfig) Reset() {
	*x = EnvelopeTriggerConfig{}
	mi := &file_proto_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeTriggerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeTriggerConfig) ProtoMessage() {}

func (x *EnvelopeTriggerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeTriggerConfig.ProtoReflect.Descriptor instead.
func (*EnvelopeTriggerConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{2}
}

func (x *EnvelopeTriggerConfig) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *EnvelopeTriggerConfig) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

type SignalFingerprintConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Iterations    uint32                 `protobuf:"varint,2,opt,name=iterations,proto3" json:"iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalFingerprintConfig) Reset() {
	*x = SignalFingerprintConfig{}
	mi := &file_proto_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalFingerprintConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalFingerprintConfig) ProtoMessage() {}

func (x *SignalFingerprintConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalFingerprintConfig.ProtoReflect.Descriptor instead.
func (*SignalFingerprintConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{3}
}

func (x *SignalFingerprintConfig) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SignalFingerprintConfig) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

type SignalFingerprintInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalId       string                 `protobuf:"bytes,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	LocalKey      string                 `protobuf:"bytes,2,opt,name=local_key,json=localKey,proto3" json:"local_key,omitempty"`
	RemoteId      string                 `protobuf:"bytes,3,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	RemoteKey     string                 `protobuf:"bytes,4,opt,name=remote_key,json=remoteKey,proto3" json:"remote_key,omitempty"`
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Iterations    uint32                 `protobuf:"varint,6,opt,name=iterations,proto3" json:"iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalFingerprintInput) Reset() {
	*x = SignalFingerprintInput{}
	mi := &file_proto_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalFingerprintInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalFingerprintInput) ProtoMessage() {}

func (x *SignalFingerprintInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalFingerprintInput.ProtoReflect.Descriptor instead.
func (*SignalFingerprintInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{4}
}

func (x *SignalFingerprintInput) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *SignalFingerprintInput) GetLocalKey() string {
	if x != nil {
		return x.LocalKey
	}
	return ""
}

func (x *SignalFingerprintInput) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *SignalFingerprintInput) GetRemoteKey() string {
	if x != nil {
		return x.RemoteKey
	}
	return ""
}

func (x *SignalFingerprintInput) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SignalFingerprintInput) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

type SignalFingerprintOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       string                 `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty"`
	ScannableHex  string                 `protobuf:"bytes,2,opt,name=scannable_hex,json=scannableHex,proto3" json:"scannable_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalFingerprintOutput) Reset() {
	*x = SignalFingerprintOutput{}
	mi := &file_proto_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalFingerprintOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalFingerprintOutput) ProtoMessage() {}

func (x *SignalFingerprintOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalFingerprintOutput.ProtoReflect.Descriptor instead.
func (*SignalFingerprintOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{5}
}

func (x *SignalFingerprintOutput) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *SignalFingerprintOutput) GetScannableHex() string {
	if x != nil {
		return x.ScannableHex
	}
	return ""
}

type SessionPrepareConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef   string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPrepareConfig) Reset() {
	*x = SessionPrepareConfig{}
	mi := &file_proto_signal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPrepareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPrepareConfig) ProtoMessage() {}

func (x *SessionPrepareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPrepareConfig.ProtoReflect.Descriptor instead.
func (*SessionPrepareConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{6}
}

func (x *SessionPrepareConfig) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

type SessionPrepareInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef   string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPrepareInput) Reset() {
	*x = SessionPrepareInput{}
	mi := &file_proto_signal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPrepareInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPrepareInput) ProtoMessage() {}

func (x *SessionPrepareInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPrepareInput.ProtoReflect.Descriptor instead.
func (*SessionPrepareInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{7}
}

func (x *SessionPrepareInput) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

type PreKeyBundle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef           string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	LocalId               string                 `protobuf:"bytes,2,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	DeviceId              uint32                 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RegistrationId        uint32                 `protobuf:"varint,4,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	PreKeyId              uint32                 `protobuf:"varint,5,opt,name=pre_key_id,json=preKeyId,proto3" json:"pre_key_id,omitempty"`
	PreKey                string                 `protobuf:"bytes,6,opt,name=pre_key,json=preKey,proto3" json:"pre_key,omitempty"`
	SignedPreKeyId        uint32                 `protobuf:"varint,7,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	SignedPreKey          string                 `protobuf:"bytes,8,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	SignedPreKeySignature string                 `protobuf:"bytes,9,opt,name=signed_pre_key_signature,json=signedPreKeySignature,proto3" json:"signed_pre_key_signature,omitempty"`
	KyberPreKeyId         uint32                 `protobuf:"varint,10,opt,name=kyber_pre_key_id,json=kyberPreKeyId,proto3" json:"kyber_pre_key_id,omitempty"`
	KyberPreKey           string                 `protobuf:"bytes,11,opt,name=kyber_pre_key,json=kyberPreKey,proto3" json:"kyber_pre_key,omitempty"`
	KyberPreKeySignature  string                 `protobuf:"bytes,12,opt,name=kyber_pre_key_signature,json=kyberPreKeySignature,proto3" json:"kyber_pre_key_signature,omitempty"`
	IdentityKey           string                 `protobuf:"bytes,13,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PreKeyBundle) Reset() {
	*x = PreKeyBundle{}
	mi := &file_proto_signal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyBundle) ProtoMessage() {}

func (x *PreKeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyBundle.ProtoReflect.Descriptor instead.
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{8}
}

func (x *PreKeyBundle) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

func (x *PreKeyBundle) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *PreKeyBundle) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PreKeyBundle) GetRegistrationId() uint32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

func (x *PreKeyBundle) GetPreKeyId() uint32 {
	if x != nil {
		return x.PreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetPreKey() string {
	if x != nil {
		return x.PreKey
	}
	return ""
}

func (x *PreKeyBundle) GetSignedPreKeyId() uint32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetSignedPreKey() string {
	if x != nil {
		return x.SignedPreKey
	}
	return ""
}

func (x *PreKeyBundle) GetSignedPreKeySignature() string {
	if x != nil {
		return x.SignedPreKeySignature
	}
	return ""
}

func (x *PreKeyBundle) GetKyberPreKeyId() uint32 {
	if x != nil {
		return x.KyberPreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetKyberPreKey() string {
	if x != nil {
		return x.KyberPreKey
	}
	return ""
}

func (x *PreKeyBundle) GetKyberPreKeySignature() string {
	if x != nil {
		return x.KyberPreKeySignature
	}
	return ""
}

func (x *PreKeyBundle) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

type SessionPrepareOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *PreKeyBundle          `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPrepareOutput) Reset() {
	*x = SessionPrepareOutput{}
	mi := &file_proto_signal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPrepareOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPrepareOutput) ProtoMessage() {}

func (x *SessionPrepareOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPrepareOutput.ProtoReflect.Descriptor instead.
func (*SessionPrepareOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{9}
}

func (x *SessionPrepareOutput) GetBundle() *PreKeyBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type SignalEncryptConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef   string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEncryptConfig) Reset() {
	*x = SignalEncryptConfig{}
	mi := &file_proto_signal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEncryptConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEncryptConfig) ProtoMessage() {}

func (x *SignalEncryptConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEncryptConfig.ProtoReflect.Descriptor instead.
func (*SignalEncryptConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{10}
}

func (x *SignalEncryptConfig) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

type SignalEncryptInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef    string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	RemoteId       string                 `protobuf:"bytes,2,opt,name=remote_id,json=remoteId,proto3" json:"remote_id,omitempty"`
	RemoteDeviceId uint32                 `protobuf:"varint,3,opt,name=remote_device_id,json=remoteDeviceId,proto3" json:"remote_device_id,omitempty"`
	RemoteBundle   *PreKeyBundle          `protobuf:"bytes,4,opt,name=remote_bundle,json=remoteBundle,proto3" json:"remote_bundle,omitempty"`
	Plaintext      []byte                 `protobuf:"bytes,5,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignalEncryptInput) Reset() {
	*x = SignalEncryptInput{}
	mi := &file_proto_signal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEncryptInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEncryptInput) ProtoMessage() {}

func (x *SignalEncryptInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEncryptInput.ProtoReflect.Descriptor instead.
func (*SignalEncryptInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{11}
}

func (x *SignalEncryptInput) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

func (x *SignalEncryptInput) GetRemoteId() string {
	if x != nil {
		return x.RemoteId
	}
	return ""
}

func (x *SignalEncryptInput) GetRemoteDeviceId() uint32 {
	if x != nil {
		return x.RemoteDeviceId
	}
	return 0
}

func (x *SignalEncryptInput) GetRemoteBundle() *PreKeyBundle {
	if x != nil {
		return x.RemoteBundle
	}
	return nil
}

func (x *SignalEncryptInput) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type SignalEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SenderId          string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderDeviceId    uint32                 `protobuf:"varint,2,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	RecipientId       string                 `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	RecipientDeviceId uint32                 `protobuf:"varint,4,opt,name=recipient_device_id,json=recipientDeviceId,proto3" json:"recipient_device_id,omitempty"`
	MessageType       string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Ciphertext        []byte                 `protobuf:"bytes,6,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignalEnvelope) Reset() {
	*x = SignalEnvelope{}
	mi := &file_proto_signal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEnvelope) ProtoMessage() {}

func (x *SignalEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEnvelope.ProtoReflect.Descriptor instead.
func (*SignalEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{12}
}

func (x *SignalEnvelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SignalEnvelope) GetSenderDeviceId() uint32 {
	if x != nil {
		return x.SenderDeviceId
	}
	return 0
}

func (x *SignalEnvelope) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SignalEnvelope) GetRecipientDeviceId() uint32 {
	if x != nil {
		return x.RecipientDeviceId
	}
	return 0
}

func (x *SignalEnvelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SignalEnvelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type SignalEncryptOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *SignalEnvelope        `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEncryptOutput) Reset() {
	*x = SignalEncryptOutput{}
	mi := &file_proto_signal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEncryptOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEncryptOutput) ProtoMessage() {}

func (x *SignalEncryptOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEncryptOutput.ProtoReflect.Descriptor instead.
func (*SignalEncryptOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{13}
}

func (x *SignalEncryptOutput) GetEnvelope() *SignalEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type SignalDecryptConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef       string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	RequiredPrincipal string                 `protobuf:"bytes,2,opt,name=required_principal,json=requiredPrincipal,proto3" json:"required_principal,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignalDecryptConfig) Reset() {
	*x = SignalDecryptConfig{}
	mi := &file_proto_signal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalDecryptConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalDecryptConfig) ProtoMessage() {}

func (x *SignalDecryptConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalDecryptConfig.ProtoReflect.Descriptor instead.
func (*SignalDecryptConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{14}
}

func (x *SignalDecryptConfig) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

func (x *SignalDecryptConfig) GetRequiredPrincipal() string {
	if x != nil {
		return x.RequiredPrincipal
	}
	return ""
}

type SignalDecryptInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityRef   string                 `protobuf:"bytes,1,opt,name=identity_ref,json=identityRef,proto3" json:"identity_ref,omitempty"`
	Principal     string                 `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Envelope      *SignalEnvelope        `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalDecryptInput) Reset() {
	*x = SignalDecryptInput{}
	mi := &file_proto_signal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalDecryptInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalDecryptInput) ProtoMessage() {}

func (x *SignalDecryptInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalDecryptInput.ProtoReflect.Descriptor instead.
func (*SignalDecryptInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{15}
}

func (x *SignalDecryptInput) GetIdentityRef() string {
	if x != nil {
		return x.IdentityRef
	}
	return ""
}

func (x *SignalDecryptInput) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *SignalDecryptInput) GetEnvelope() *SignalEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type SignalDecryptOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denied        bool                   `protobuf:"varint,1,opt,name=denied,proto3" json:"denied,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalDecryptOutput) Reset() {
	*x = SignalDecryptOutput{}
	mi := &file_proto_signal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalDecryptOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalDecryptOutput) ProtoMessage() {}

func (x *SignalDecryptOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalDecryptOutput.ProtoReflect.Descriptor instead.
func (*SignalDecryptOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{16}
}

func (x *SignalDecryptOutput) GetDenied() bool {
	if x != nil {
		return x.Denied
	}
	return false
}

func (x *SignalDecryptOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SignalDecryptOutput) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type AccountKeysConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntropyPool     string                 `protobuf:"bytes,1,opt,name=entropy_pool,json=entropyPool,proto3" json:"entropy_pool,omitempty"`
	Aci             []byte                 `protobuf:"bytes,2,opt,name=aci,proto3" json:"aci,omitempty"`
	Pin             string                 `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	PinSalt         []byte                 `protobuf:"bytes,4,opt,name=pin_salt,json=pinSalt,proto3" json:"pin_salt,omitempty"`
	PinSaltUsername string                 `protobuf:"bytes,5,opt,name=pin_salt_username,json=pinSaltUsername,proto3" json:"pin_salt_username,omitempty"`
	PinSaltGroupId  uint64                 `protobuf:"varint,6,opt,name=pin_salt_group_id,json=pinSaltGroupId,proto3" json:"pin_salt_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountKeysConfig) Reset() {
	*x = AccountKeysConfig{}
	mi := &file_proto_signal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountKeysConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKeysConfig) ProtoMessage() {}

func (x *AccountKeysConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKeysConfig.ProtoReflect.Descriptor instead.
func (*AccountKeysConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{17}
}

func (x *AccountKeysConfig) GetEntropyPool() string {
	if x != nil {
		return x.EntropyPool
	}
	return ""
}

func (x *AccountKeysConfig) GetAci() []byte {
	if x != nil {
		return x.Aci
	}
	return nil
}

func (x *AccountKeysConfig) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *AccountKeysConfig) GetPinSalt() []byte {
	if x != nil {
		return x.PinSalt
	}
	return nil
}

func (x *AccountKeysConfig) GetPinSaltUsername() string {
	if x != nil {
		return x.PinSaltUsername
	}
	return ""
}

func (x *AccountKeysConfig) GetPinSaltGroupId() uint64 {
	if x != nil {
		return x.PinSaltGroupId
	}
	return 0
}

type AccountKeysInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntropyPool     string                 `protobuf:"bytes,1,opt,name=entropy_pool,json=entropyPool,proto3" json:"entropy_pool,omitempty"`
	Aci             []byte                 `protobuf:"bytes,2,opt,name=aci,proto3" json:"aci,omitempty"`
	Pin             string                 `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	PinSalt         []byte                 `protobuf:"bytes,4,opt,name=pin_salt,json=pinSalt,proto3" json:"pin_salt,omitempty"`
	PinSaltUsername string                 `protobuf:"bytes,5,opt,name=pin_salt_username,json=pinSaltUsername,proto3" json:"pin_salt_username,omitempty"`
	PinSaltGroupId  uint64                 `protobuf:"varint,6,opt,name=pin_salt_group_id,json=pinSaltGroupId,proto3" json:"pin_salt_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountKeysInput) Reset() {
	*x = AccountKeysInput{}
	mi := &file_proto_signal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountKeysInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKeysInput) ProtoMessage() {}

func (x *AccountKeysInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKeysInput.ProtoReflect.Descriptor instead.
func (*AccountKeysInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{18}
}

func (x *AccountKeysInput) GetEntropyPool() string {
	if x != nil {
		return x.EntropyPool
	}
	return ""
}

func (x *AccountKeysInput) GetAci() []byte {
	if x != nil {
		return x.Aci
	}
	return nil
}

func (x *AccountKeysInput) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *AccountKeysInput) GetPinSalt() []byte {
	if x != nil {
		return x.PinSalt
	}
	return nil
}

func (x *AccountKeysInput) GetPinSaltUsername() string {
	if x != nil {
		return x.PinSaltUsername
	}
	return ""
}

func (x *AccountKeysInput) GetPinSaltGroupId() uint64 {
	if x != nil {
		return x.PinSaltGroupId
	}
	return 0
}

type AccountKeysOutput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntropyPool      string                 `protobuf:"bytes,1,opt,name=entropy_pool,json=entropyPool,proto3" json:"entropy_pool,omitempty"`
	SvrKey           []byte                 `protobuf:"bytes,2,opt,name=svr_key,json=svrKey,proto3" json:"svr_key,omitempty"`
	BackupKey        []byte                 `protobuf:"bytes,3,opt,name=backup_key,json=backupKey,proto3" json:"backup_key,omitempty"`
	BackupId         []byte                 `protobuf:"bytes,4,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	PinSalt          []byte                 `protobuf:"bytes,5,opt,name=pin_salt,json=pinSalt,proto3" json:"pin_salt,omitempty"`
	PinAccessKey     []byte                 `protobuf:"bytes,6,opt,name=pin_access_key,json=pinAccessKey,proto3" json:"pin_access_key,omitempty"`
	PinEncryptionKey []byte                 `protobuf:"bytes,7,opt,name=pin_encryption_key,json=pinEncryptionKey,proto3" json:"pin_encryption_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountKeysOutput) Reset() {
	*x = AccountKeysOutput{}
	mi := &file_proto_signal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountKeysOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKeysOutput) ProtoMessage() {}

func (x *AccountKeysOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKeysOutput.ProtoReflect.Descriptor instead.
func (*AccountKeysOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{19}
}

func (x *AccountKeysOutput) GetEntropyPool() string {
	if x != nil {
		return x.EntropyPool
	}
	return ""
}

func (x *AccountKeysOutput) GetSvrKey() []byte {
	if x != nil {
		return x.SvrKey
	}
	return nil
}

func (x *AccountKeysOutput) GetBackupKey() []byte {
	if x != nil {
		return x.BackupKey
	}
	return nil
}

func (x *AccountKeysOutput) GetBackupId() []byte {
	if x != nil {
		return x.BackupId
	}
	return nil
}

func (x *AccountKeysOutput) GetPinSalt() []byte {
	if x != nil {
		return x.PinSalt
	}
	return nil
}

func (x *AccountKeysOutput) GetPinAccessKey() []byte {
	if x != nil {
		return x.PinAccessKey
	}
	return nil
}

func (x *AccountKeysOutput) GetPinEncryptionKey() []byte {
	if x != nil {
		return x.PinEncryptionKey
	}
	return nil
}

type UsernameLinkCreateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Entropy       []byte                 `protobuf:"bytes,2,opt,name=entropy,proto3" json:"entropy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameLinkCreateConfig) Reset() {
	*x = UsernameLinkCreateConfig{}
	mi := &file_proto_signal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLinkCreateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLinkCreateConfig) ProtoMessage() {}

func (x *UsernameLinkCreateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLinkCreateConfig.ProtoReflect.Descriptor instead.
func (*UsernameLinkCreateConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{20}
}

func (x *UsernameLinkCreateConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernameLinkCreateConfig) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

type UsernameLinkCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Entropy       []byte                 `protobuf:"bytes,2,opt,name=entropy,proto3" json:"entropy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameLinkCreateInput) Reset() {
	*x = UsernameLinkCreateInput{}
	mi := &file_proto_signal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLinkCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLinkCreateInput) ProtoMessage() {}

func (x *UsernameLinkCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLinkCreateInput.ProtoReflect.Descriptor instead.
func (*UsernameLinkCreateInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{21}
}

func (x *UsernameLinkCreateInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernameLinkCreateInput) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

type UsernameLinkCreateOutput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Entropy           []byte                 `protobuf:"bytes,1,opt,name=entropy,proto3" json:"entropy,omitempty"`
	EncryptedUsername []byte                 `protobuf:"bytes,2,opt,name=encrypted_username,json=encryptedUsername,proto3" json:"encrypted_username,omitempty"`
	LinkBuffer        []byte                 `protobuf:"bytes,3,opt,name=link_buffer,json=linkBuffer,proto3" json:"link_buffer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UsernameLinkCreateOutput) Reset() {
	*x = UsernameLinkCreateOutput{}
	mi := &file_proto_signal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLinkCreateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLinkCreateOutput) ProtoMessage() {}

func (x *UsernameLinkCreateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLinkCreateOutput.ProtoReflect.Descriptor instead.
func (*UsernameLinkCreateOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{22}
}

func (x *UsernameLinkCreateOutput) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

func (x *UsernameLinkCreateOutput) GetEncryptedUsername() []byte {
	if x != nil {
		return x.EncryptedUsername
	}
	return nil
}

func (x *UsernameLinkCreateOutput) GetLinkBuffer() []byte {
	if x != nil {
		return x.LinkBuffer
	}
	return nil
}

type UsernameLinkDecryptConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entropy       []byte                 `protobuf:"bytes,1,opt,name=entropy,proto3" json:"entropy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameLinkDecryptConfig) Reset() {
	*x = UsernameLinkDecryptConfig{}
	mi := &file_proto_signal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLinkDecryptConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLinkDecryptConfig) ProtoMessage() {}

func (x *UsernameLinkDecryptConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLinkDecryptConfig.ProtoReflect.Descriptor instead.
func (*UsernameLinkDecryptConfig) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{23}
}

func (x *UsernameLinkDecryptConfig) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

type UsernameLinkDecryptInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Entropy           []byte                 `protobuf:"bytes,1,opt,name=entropy,proto3" json:"entropy,omitempty"`
	EncryptedUsername []byte                 `protobuf:"bytes,2,opt,name=encrypted_username,json=encryptedUsername,proto3" json:"encrypted_username,omitempty"`
	LinkBuffer        []byte                 `protobuf:"bytes,3,opt,name=link_buffer,json=linkBuffer,proto3" json:"link_buffer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UsernameLinkDecryptInput) Reset() {
	*x = UsernameLinkDecryptInput{}
	mi := &file_proto_signal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLinkDecryptInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLinkDecryptInput) ProtoMessage() {}

func (x *UsernameLinkDecryptInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLinkDecryptInput.ProtoReflect.Descriptor instead.
func (*UsernameLinkDecryptInput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{24}
}

func (x *UsernameLinkDecryptInput) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

func (x *UsernameLinkDecryptInput) GetEncryptedUsername() []byte {
	if x != nil {
		return x.EncryptedUsername
	}
	return nil
}

func (x *UsernameLinkDecryptInput) GetLinkBuffer() []byte {
	if x != nil {
		return x.LinkBuffer
	}
	return nil
}

type UsernameLinkDecryptOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameLinkDecryptOutput) Reset() {
	*x = UsernameLinkDecryptOutput{}
	mi := &file_proto_signal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameLinkDecryptOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameLinkDecryptOutput) ProtoMessage() {}

func (x *UsernameLinkDecryptOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameLinkDecryptOutput.ProtoReflect.Descriptor instead.
func (*UsernameLinkDecryptOutput) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{25}
}

func (x *UsernameLinkDecryptOutput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_proto_signal_proto protoreflect.FileDescriptor

const file_proto_signal_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signal.proto\x12\x1aworkflow.plugins.signal.v1\"\x99\x01\n" +
	"\x13IdentityStoreConfig\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\x12\x19\n" +
	"\blocal_id\x18\x02 \x01(\tR\alocalId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\rR\bdeviceId\x12'\n" +
	"\x0fregistration_id\x18\x04 \x01(\rR\x0eregistrationId\"\x8b\x01\n" +
	"\vSpaceConfig\x12\x1b\n" +
	"\tspace_ref\x18\x01 \x01(\tR\bspaceRef\x12!\n" +
	"\fidentity_ref\x18\x02 \x01(\tR\videntityRef\x12\x19\n" +
	"\broom_ref\x18\x03 \x01(\tR\aroomRef\x12!\n" +
	"\feventbus_ref\x18\x04 \x01(\tR\veventbusRef\"Y\n" +
	"\x15EnvelopeTriggerConfig\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x01 \x01(\tR\tsourceRef\x12!\n" +
	"\fidentity_ref\x18\x02 \x01(\tR\videntityRef\"S\n" +
	"\x17SignalFingerprintConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1e\n" +
	"\n" +
	"iterations\x18\x02 \x01(\rR\n" +
	"iterations\"\xc6\x01\n" +
	"\x16SignalFingerprintInput\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\tR\alocalId\x12\x1b\n" +
	"\tlocal_key\x18\x02 \x01(\tR\blocalKey\x12\x1b\n" +
	"\tremote_id\x18\x03 \x01(\tR\bremoteId\x12\x1d\n" +
	"\n" +
	"remote_key\x18\x04 \x01(\tR\tremoteKey\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x1e\n" +
	"\n" +
	"iterations\x18\x06 \x01(\rR\n" +
	"iterations\"X\n" +
	"\x17SignalFingerprintOutput\x12\x18\n" +
	"\adisplay\x18\x01 \x01(\tR\adisplay\x12#\n" +
	"\rscannable_hex\x18\x02 \x01(\tR\fscannableHex\"9\n" +
	"\x14SessionPrepareConfig\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\"8\n" +
	"\x13SessionPrepareInput\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\"\xfa\x03\n" +
	"\fPreKeyBundle\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\x12\x19\n" +
	"\blocal_id\x18\x02 \x01(\tR\alocalId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\rR\bdeviceId\x12'\n" +
	"\x0fregistration_id\x18\x04 \x01(\rR\x0eregistrationId\x12\x1c\n" +
	"\n" +
	"pre_key_id\x18\x05 \x01(\rR\bpreKeyId\x12\x17\n" +
	"\apre_key\x18\x06 \x01(\tR\x06preKey\x12)\n" +
	"\x11signed_pre_key_id\x18\a \x01(\rR\x0esignedPreKeyId\x12$\n" +
	"\x0esigned_pre_key\x18\b \x01(\tR\fsignedPreKey\x127\n" +
	"\x18signed_pre_key_signature\x18\t \x01(\tR\x15signedPreKeySignature\x12'\n" +
	"\x10kyber_pre_key_id\x18\n" +
	" \x01(\rR\rkyberPreKeyId\x12\"\n" +
	"\rkyber_pre_key\x18\v \x01(\tR\vkyberPreKey\x125\n" +
	"\x17kyber_pre_key_signature\x18\f \x01(\tR\x14kyberPreKeySignature\x12!\n" +
	"\fidentity_key\x18\r \x01(\tR\videntityKey\"X\n" +
	"\x14SessionPrepareOutput\x12@\n" +
	"\x06bundle\x18\x01 \x01(\v2(.workflow.plugins.signal.v1.PreKeyBundleR\x06bundle\"8\n" +
	"\x13SignalEncryptConfig\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\"\xeb\x01\n" +
	"\x12SignalEncryptInput\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\x12\x1b\n" +
	"\tremote_id\x18\x02 \x01(\tR\bremoteId\x12(\n" +
	"\x10remote_device_id\x18\x03 \x01(\rR\x0eremoteDeviceId\x12M\n" +
	"\rremote_bundle\x18\x04 \x01(\v2(.workflow.plugins.signal.v1.PreKeyBundleR\fremoteBundle\x12\x1c\n" +
	"\tplaintext\x18\x05 \x01(\fR\tplaintext\"\xed\x01\n" +
	"\x0eSignalEnvelope\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12(\n" +
	"\x10sender_device_id\x18\x02 \x01(\rR\x0esenderDeviceId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\tR\vrecipientId\x12.\n" +
	"\x13recipient_device_id\x18\x04 \x01(\rR\x11recipientDeviceId\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x06 \x01(\fR\n" +
	"ciphertext\"]\n" +
	"\x13SignalEncryptOutput\x12F\n" +
	"\benvelope\x18\x01 \x01(\v2*.workflow.plugins.signal.v1.SignalEnvelopeR\benvelope\"g\n" +
	"\x13SignalDecryptConfig\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\x12-\n" +
	"\x12required_principal\x18\x02 \x01(\tR\x11requiredPrincipal\"\x9d\x01\n" +
	"\x12SignalDecryptInput\x12!\n" +
	"\fidentity_ref\x18\x01 \x01(\tR\videntityRef\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\x12F\n" +
	"\benvelope\x18\x03 \x01(\v2*.workflow.plugins.signal.v1.SignalEnvelopeR\benvelope\"a\n" +
	"\x13SignalDecryptOutput\x12\x16\n" +
	"\x06denied\x18\x01 \x01(\bR\x06denied\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\tplaintext\x18\x03 \x01(\fR\tplaintext\"\xcc\x01\n" +
	"\x11AccountKeysConfig\x12!\n" +
	"\fentropy_pool\x18\x01 \x01(\tR\ventropyPool\x12\x10\n" +
	"\x03aci\x18\x02 \x01(\fR\x03aci\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\tR\x03pin\x12\x19\n" +
	"\bpin_salt\x18\x04 \x01(\fR\apinSalt\x12*\n" +
	"\x11pin_salt_username\x18\x05 \x01(\tR\x0fpinSaltUsername\x12)\n" +
	"\x11pin_salt_group_id\x18\x06 \x01(\x04R\x0epinSaltGroupId\"\xcb\x01\n" +
	"\x10AccountKeysInput\x12!\n" +
	"\fentropy_pool\x18\x01 \x01(\tR\ventropyPool\x12\x10\n" +
	"\x03aci\x18\x02 \x01(\fR\x03aci\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\tR\x03pin\x12\x19\n" +
	"\bpin_salt\x18\x04 \x01(\fR\apinSalt\x12*\n" +
	"\x11pin_salt_username\x18\x05 \x01(\tR\x0fpinSaltUsername\x12)\n" +
	"\x11pin_salt_group_id\x18\x06 \x01(\x04R\x0epinSaltGroupId\"\xfa\x01\n" +
	"\x11AccountKeysOutput\x12!\n" +
	"\fentropy_pool\x18\x01 \x01(\tR\ventropyPool\x12\x17\n" +
	"\asvr_key\x18\x02 \x01(\fR\x06svrKey\x12\x1d\n" +
	"\n" +
	"backup_key\x18\x03 \x01(\fR\tbackupKey\x12\x1b\n" +
	"\tbackup_id\x18\x04 \x01(\fR\bbackupId\x12\x19\n" +
	"\bpin_salt\x18\x05 \x01(\fR\apinSalt\x12$\n" +
	"\x0epin_access_key\x18\x06 \x01(\fR\fpinAccessKey\x12,\n" +
	"\x12pin_encryption_key\x18\a \x01(\fR\x10pinEncryptionKey\"P\n" +
	"\x18UsernameLinkCreateConfig\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aentropy\x18\x02 \x01(\fR\aentropy\"O\n" +
	"\x17UsernameLinkCreateInput\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aentropy\x18\x02 \x01(\fR\aentropy\"\x84\x01\n" +
	"\x18UsernameLinkCreateOutput\x12\x18\n" +
	"\aentropy\x18\x01 \x01(\fR\aentropy\x12-\n" +
	"\x12encrypted_username\x18\x02 \x01(\fR\x11encryptedUsername\x12\x1f\n" +
	"\vlink_buffer\x18\x03 \x01(\fR\n" +
	"linkBuffer\"5\n" +
	"\x19UsernameLinkDecryptConfig\x12\x18\n" +
	"\aentropy\x18\x01 \x01(\fR\aentropy\"\x84\x01\n" +
	"\x18UsernameLinkDecryptInput\x12\x18\n" +
	"\aentropy\x18\x01 \x01(\fR\aentropy\x12-\n" +
	"\x12encrypted_username\x18\x02 \x01(\fR\x11encryptedUsername\x12\x1f\n" +
	"\vlink_buffer\x18\x03 \x01(\fR\n" +
	"linkBuffer\"7\n" +
	"\x19UsernameLinkDecryptOutput\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busernameBBZ@github.com/GoCodeAlone/workflow-plugin-signal/internal/contractsb\x06proto3"

var (
	file_proto_signal_proto_rawDescOnce sync.Once
	file_proto_signal_proto_rawDescData []byte
)

func file_proto_signal_proto_rawDescGZIP() []byte {
	file_proto_signal_proto_rawDescOnce.Do(func() {
		file_proto_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)))
	})
	return file_proto_signal_proto_rawDescData
}

var file_proto_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_signal_proto_goTypes = []any{
	(*IdentityStoreConfig)(nil),       // 0: workflow.plugins.signal.v1.IdentityStoreConfig
	(*SpaceConfig)(nil),               // 1: workflow.plugins.signal.v1.SpaceConfig
	(*EnvelopeTriggerConfig)(nil),     // 2: workflow.plugins.signal.v1.EnvelopeTriggerConfig
	(*SignalFingerprintConfig)(nil),   // 3: workflow.plugins.signal.v1.SignalFingerprintConfig
	(*SignalFingerprintInput)(nil),    // 4: workflow.plugins.signal.v1.SignalFingerprintInput
	(*SignalFingerprintOutput)(nil),   // 5: workflow.plugins.signal.v1.SignalFingerprintOutput
	(*SessionPrepareConfig)(nil),      // 6: workflow.plugins.signal.v1.SessionPrepareConfig
	(*SessionPrepareInput)(nil),       // 7: workflow.plugins.signal.v1.SessionPrepareInput
	(*PreKeyBundle)(nil),              // 8: workflow.plugins.signal.v1.PreKeyBundle
	(*SessionPrepareOutput)(nil),      // 9: workflow.plugins.signal.v1.SessionPrepareOutput
	(*SignalEncryptConfig)(nil),       // 10: workflow.plugins.signal.v1.SignalEncryptConfig
	(*SignalEncryptInput)(nil),        // 11: workflow.plugins.signal.v1.SignalEncryptInput
	(*SignalEnvelope)(nil),            // 12: workflow.plugins.signal.v1.SignalEnvelope
	(*SignalEncryptOutput)(nil),       // 13: workflow.plugins.signal.v1.SignalEncryptOutput
	(*SignalDecryptConfig)(nil),       // 14: workflow.plugins.signal.v1.SignalDecryptConfig
	(*SignalDecryptInput)(nil),        // 15: workflow.plugins.signal.v1.SignalDecryptInput
	(*SignalDecryptOutput)(nil),       // 16: workflow.plugins.signal.v1.SignalDecryptOutput
	(*AccountKeysConfig)(nil),         // 17: workflow.plugins.signal.v1.AccountKeysConfig
	(*AccountKeysInput)(nil),          // 18: workflow.plugins.signal.v1.AccountKeysInput
	(*AccountKeysOutput)(nil),         // 19: workflow.plugins.signal.v1.AccountKeysOutput
	(*UsernameLinkCreateConfig)(nil),  // 20: workflow.plugins.signal.v1.UsernameLinkCreateConfig
	(*UsernameLinkCreateInput)(nil),   // 21: workflow.plugins.signal.v1.UsernameLinkCreateInput
	(*UsernameLinkCreateOutput)(nil),  // 22: workflow.plugins.signal.v1.UsernameLinkCreateOutput
	(*UsernameLinkDecryptConfig)(nil), // 23: workflow.plugins.signal.v1.UsernameLinkDecryptConfig
	(*UsernameLinkDecryptInput)(nil),  // 24: workflow.plugins.signal.v1.UsernameLinkDecryptInput
	(*UsernameLinkDecryptOutput)(nil), // 25: workflow.plugins.signal.v1.UsernameLinkDecryptOutput
}
var file_proto_signal_proto_depIdxs = []int32{
	8,  // 0: workflow.plugins.signal.v1.SessionPrepareOutput.bundle:type_name -> workflow.plugins.signal.v1.PreKeyBundle
	8,  // 1: workflow.plugins.signal.v1.SignalEncryptInput.remote_bundle:type_name -> workflow.plugins.signal.v1.PreKeyBundle
	12, // 2: workflow.plugins.signal.v1.SignalEncryptOutput.envelope:type_name -> workflow.plugins.signal.v1.SignalEnvelope
	12, // 3: workflow.plugins.signal.v1.SignalDecryptInput.envelope:type_name -> workflow.plugins.signal.v1.SignalEnvelope
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_signal_proto_init() }
func file_proto_signal_proto_init() {
	if File_proto_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_signal_proto_goTypes,
		DependencyIndexes: file_proto_signal_proto_depIdxs,
		MessageInfos:      file_proto_signal_proto_msgTypes,
	}.Build()
	File_proto_signal_proto = out.File
	file_proto_signal_proto_goTypes = nil
	file_proto_signal_proto_depIdxs = nil
}
